### ISSUE TITLE
How to disable echo?

### ISSUE THREAD

**Issue by vinllen** [ziutek/telnet#10]
The code `SetEcho(false)` doesn't work in your code, but when I use `telnet` command in Linux shell, the echo mode is disabled.

**Comment by ziutek** [comment]
The description of SetEcho method clearly says: "SetEcho tries to enable/disable echo on server side. Typically telnet servers doesn't support this."

The echo can be probably only disabled by a process that runs on the server side (eg: the Unix login program does this when you type password).

**Comment by vinllen** [comment]
Hi, Ziutek.I think there must be a way to disable echo on the client side so that every command won't be echo anymore. `telnet` command is a client in Linux shell, but there is no echo in this client.

**Comment by ziutek** [comment]
Yes. You can simply stop print anything you receive from server.

**Comment by vinllen** [comment]
But how to judge whether it's an echo packet or not in an easy way? It's easy when I start only one goroutine that sends a message after receiving, however, I use two goroutines that one for reading while the other for writing.

**Comment by ziutek** [comment]
It seems that you still don't understand the problem with echo.

I don't known your specific case, but the problem insist in (99% probability) that in your case, the echo isn't produced by telnet server but by your remote operating system/application (I don't known any server that supports echo option). If this OS/application doesn't support option to disable echo, its output will be mixed with your input.

If the remote system is Unix/Linux  and you have access to the shell, you can disable echo using:

```shell
stty -echo
````
command.

**Comment by vinllen** [comment]
Hi, Ziutek, thanks for your reply, sorry for my unclear description. Actually, after disabling the echo option in your code, these question has been moving forwarding but still troubled me for some days. 
I'm writing a proxy that forwards some messages between a socket and a router, here comes my forwarding code: 
```
func handle(northConn net.Conn) {
    //.... // code omit, 1. handle the connection from remote
    
    telnetConn, err := telnet.Dial("tcp", socketPair) // 2. use telnet library

    passUsername() // 3. Pass username and password in "expect" way

    transport(northConn, telnetConn.Conn) // 4. just forwarding message
}
func transport(rw1, rw2 io.ReadWriter) error {
    errc := make(chan error, 1)
    go func() {
        _, err := io.Copy(rw1, rw2)
        errc <- err
    }()

    go func() {
        _, err := io.Copy(rw2, rw1)
        errc <- err
    }()

    err := <-errc
    if err != nil && err == io.EOF {
        err = nil
    }
    return err
}
```
In this case, `rw1` is a socket used to connect to remote client A, `rw2` is a socket that used to telnet to a router by your library.
I disabled the echo option in your code:
```
	case optEcho:
		// Accept any echo configuration.
		switch cmd {
		case cmdDo:
			if !c.cliEcho {
				c.cliEcho = true
				err = c.will(o)
			}
		case cmdDont:
			if c.cliEcho {
				c.cliEcho = false
				err = c.wont(o)
			}
		case cmdWill:
			// err = c.do(o)
			err = c.dont(o)
		case cmdWont:
			err = c.dont(o)
		}
```
Now, these option come into effect when passing the username and password in function `passUsername()` which means **no echo show**. However, in function `transport`, every command is echoed from router:
```
test-Router.Int# asdasdasd
asdasdasd                              # comment: echo command, but I want to erase it.
                              ^
% Invalid command at '^' marker.
test-Router.Int# aaaaa
aaaaa                                      # comment: echo command again
                              ^
% Invalid command at '^' marker.
test-Router.Int#
```

**Comment by ziutek** [comment]
There is a LINEMODE (currently not supported by this package) that when supported by both sides can probably do echo locally for line editing. See https://tools.ietf.org/html/rfc1184

**Comment by vinllen** [comment]
Hi, Ziutek. Thanks for your detailed explanation, it helps me a lot.
