### ISSUE TITLE
i/o time out 

### ISSUE THREAD

**Issue by 73DX** [ziutek/telnet#13]
Hello, 
I am using the main.go example to connect to 
telnet.reversebeacon.net:7000
and I receive a time out.

I can connect without any issues with other clients.
Any help?

Go version: 1.9.4
OS: Windows 7 Enterprise 64-bits.
No build errors.
Error recevied from the telnet server:
2018/02/12 18:30:33 Error: read tcp 192.168.1.5:54852->198.137.202.75:7000: i/o
timeout

Hope you can help me.
Thanks.

**Comment by ziutek** [comment]
Please share a code that can be used to reproduce this error.

**Comment by ziutek** [comment]
If you use unmodified example it will return timeout because it waits for "login:" or "name:" string and this site returns "Please enter your call:".

**Comment by 73DX** [comment]
Hello,
Thanks for your reply.
The issue has been fixed.

Thanks,
Martin

El 15 feb. 2018 8:11 p. m., "Michał Derkacz" <notifications@github.com>
escribió:

If you use unmodified example it will return timeout because it waits for
"login:" or "name:" string and this site returns "Please enter your call:".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ziutek/telnet/issues/13#issuecomment-366093326>, or mute
the thread
