### ISSUE TITLE
command data should be writeln to tcp Conn

### ISSUE THREAD

**Issue by djadala** [ziutek/telnet#8]
Hi,
conn.go line 133
https://github.com/ziutek/telnet/blob/master/conn.go#L113
```go
if _, err := c.Write(data); err != nil {
```
should be
 ```go
if _, err := c.Conn.Write(data); err != nil {
```
fix is trivial, but if you want PR, i can send one this week.

Regards,
Jamil Djadala

**Comment by ziutek** [comment]
Fixed. Thanks!
